[supabase]
SUPABASE_URL = "https://lzthpdpqlfxkkseqkhwd.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dGhwZHBxbGZ4a2tzZXFraHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMDg0NTgsImV4cCI6MjA1NDY4NDQ1OH0.Xhkn2BOfsEVdeSYNPfwa-ohNKDQpaiIJasOy8UjbnQs"